export const phone_prefixes = [
  { country: "Afganistán", iso2: "AF", prefix: "+93" },
  { country: "Alemania", iso2: "DE", prefix: "+49" },
  { country: "Argentina", iso2: "AR", prefix: "+54" },
  { country: "Australia", iso2: "AU", prefix: "+61" },
  { country: "Brasil", iso2: "BR", prefix: "+55" },
  { country: "Canadá", iso2: "CA", prefix: "+1" },
  { country: "Chile", iso2: "CL", prefix: "+56" },
  { country: "China", iso2: "CN", prefix: "+86" },
  { country: "Colombia", iso2: "CO", prefix: "+57" },
  { country: "Corea del Sur", iso2: "KR", prefix: "+82" },
  { country: "Costa Rica", iso2: "CR", prefix: "+506" },
  { country: "Ecuador", iso2: "EC", prefix: "+593" },
  { country: "El Salvador", iso2: "SV", prefix: "+503" },
  { country: "España", iso2: "ES", prefix: "+34" },
  { country: "Estados Unidos", iso2: "US", prefix: "+1" },
  { country: "Francia", iso2: "FR", prefix: "+33" },
  { country: "Guatemala", iso2: "GT", prefix: "+502" },
  { country: "Honduras", iso2: "HN", prefix: "+504" },
  { country: "India", iso2: "IN", prefix: "+91" },
  { country: "Italia", iso2: "IT", prefix: "+39" },
  { country: "Japón", iso2: "JP", prefix: "+81" },
  { country: "México", iso2: "MX", prefix: "+52" },
  { country: "Nicaragua", iso2: "NI", prefix: "+505" },
  { country: "Panamá", iso2: "PA", prefix: "+507" },
  { country: "Paraguay", iso2: "PY", prefix: "+595" },
  { country: "Perú", iso2: "PE", prefix: "+51" },
  { country: "Reino Unido", iso2: "GB", prefix: "+44" },
  { country: "República Dominicana", iso2: "DO", prefix: "+1-809" },
  { country: "Uruguay", iso2: "UY", prefix: "+598" },
  { country: "Venezuela", iso2: "VE", prefix: "+58" },
];
